### ISSUE TITLE
InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by Mailaender** [penev92/Oraide.LanguageServer#47]
```
[Info  - 12:06:35] Connection to server got closed. Server will restart.
WORKSPACE FOLDER PATH:  /home/matthias/Entwicklung/OpenRA/OpenHV
OPENRA DEFAULT FOLDER PATH:  
OPENRA CHOSEN FOLDER PATH:  /home/matthias/Entwicklung/OpenRA/OpenHV
-------------
Unhandled exception. System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Oraide.Csharp.CodeSymbolGenerationStrategies.CodeParsingSymbolGenerationStrategy..ctor(String& openRaFolder) in /home/runner/work/Oraide.LanguageServer/Oraide.LanguageServer/server/Oraide.Csharp/CodeSymbolGenerationStrategies/CodeParsingSymbolGenerationStrategy.cs:line 34
   at Oraide.Csharp.CodeInformationProvider..ctor(String workspaceFolderPath, String defaultOpenRaFolderPath) in /home/runner/work/Oraide.LanguageServer/Oraide.LanguageServer/server/Oraide.Csharp/CodeInformationProvider.cs:line 37
   at Oraide.LanguageServer.Extensions.ServiceCollectionExtensions.AddSymbolProviders(IServiceCollection serviceCollection, String workspaceFolderPath, String defaultOpenRaFolderPath) in /home/runner/work/Oraide.LanguageServer/Oraide.LanguageServer/server/Oraide.LanguageServer/Extensions/ServiceCollectionExtensions.cs:line 20
   at Oraide.LanguageServer.Program.Main(String[] args) in /home/runner/work/Oraide.LanguageServer/Oraide.LanguageServer/server/Oraide.LanguageServer/Program.cs:line 14
   at Oraide.LanguageServer.Program.<Main>(String[] args)
[Error - 12:06:35] Connection to server got closed. Server will not be restarted.
```

**Comment by penev92** [comment]
This should have been fixed in #48. Can you confirm?
